name: test python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Deps
      run: pip install -r requirements-dev.txt
    - name: Run formatting check
      run : black --check hint.py
    - name: Run PEP8 compliance check
      run: flake8 hint.py
    - name: Run type checking
      run: mypy hint.py
    - name: Run unit tests
      run: python -m unittest discover
